name: CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Share artifact
        uses: actions/upload-artifact@v1
        with:
          name: resume_project

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Get artifact
        uses: actions/download-artifact@v1
        with:
          name: resume_project

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to S3
        run: aws s3 sync . s3://east-developer-resume --delete
        working-directory: resume_project
