name: CI/CD

on: [push]

jobs:
  deploy:
  - name: Deploy to bucket
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Deploy to S3 Bucket
    run: aws s3 sync ./resume_project/ s3://east-developer-resume --delete
    